version: '3.8'
services:
  kafka-go-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-go-service
    image: kafka-go-service:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES='broker,controller'
      - KAFKA_CONTROLLER_QUORUM_VOTERS='1@kafka:9093'
      - KAFKA_LISTENERS='PLAINTEXT://:9092,CONTROLLER://:9093'
      - KAFKA_ADVERTISED_LISTENERS='PLAINTEXT://kafka:9092'
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP='CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      - KAFKA_INTER_BROKER_LISTENER_NAME='PLAINTEXT'
      - KAFKA_CONTROLLER_LISTENER_NAMES='CONTROLLER'
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - CLUSTER_ID='MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - kafka_data:/tmp/kraft-combined-logs

volumes:
  postgres_data:
  kafka_data:
